Vagrant.configure("2") do |config|

  # ~ ------------------------------------------------------------------------------------------------------------------------------------------------------
  # @ domain controller 
  config.vm.define "dc.adapt.com" do |cfg|
  cfg.vm.box = "detectionlab/win2016"
  cfg.vm.hostname = "dc-adapt-com"
  cfg.vm.boot_timeout = 600
  cfg.winrm.transport = :plaintext
  cfg.vm.communicator = "winrm"
  cfg.winrm.basic_auth_only = true
  cfg.winrm.timeout = 300
  cfg.winrm.retry_limit = 20
  cfg.vm.network :private_network, ip: "192.168.56.124", gateway: "192.168.56.1", dns: "8.8.8.8"
  
  # scripts
  cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: true, args: "-ip 192.168.56.124 -dns 8.8.8.8 -gateway 192.168.56.1" 
  
  # ! change sdc ip when settled
  cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
  cfg.vm.provision "reload"

  # ! change sdc ip when settled
  cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: false

  cfg.vm.provision "shell", path: "scripts/configure-users.ps1", privileged: false

  cfg.vm.provider "vmware_desktop" do |v, override|
    v.vmx["displayname"] = "dc.adapt.com"
    v.memory = 3072
    v.cpus = 2
    v.gui = true
  end

  cfg.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "dc.adapt.com"
    vb.default_nic_type = "82545EM"
    vb.customize ["modifyvm", :id, "--memory", 3072]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end

  cfg.vm.provider "libvirt" do |lv, override|
    lv.graphics_type = "spice"
    lv.video_type = "qxl"
    lv.input :type => "tablet", :bus => "usb"

    override.vm.box = "../Boxes/windows_2016_libvirt.box"
    lv.video_vram = 32768
    lv.memory = 3072
    lv.cpus = 2
    # This is NOT the right semantic for Vagrant synced folder. It's a workaround:
    # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11
    override.vm.synced_folder '.', '/', type: 'winrm' 
    end
  end
  # ~ ------------------------------------------------------------------------------------------------------------------------------------------------------
    # @ subdomain controller 
    config.vm.define "sdc.private.adapt.com" do |cfg|
      cfg.vm.box = "detectionlab/win2016"
      cfg.vm.hostname = "sdc-private"
      cfg.vm.boot_timeout = 600
      cfg.winrm.transport = :plaintext
      cfg.vm.communicator = "winrm"
      cfg.winrm.basic_auth_only = true
      cfg.winrm.timeout = 300
      cfg.winrm.retry_limit = 20
      cfg.vm.network :private_network, ip: "192.168.57.124", gateway: "192.168.57.1", dns: "8.8.8.8"
      
      # scripts
      cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: true, args: "-ip 192.168.57.124 -dns 8.8.8.8 -gateway 192.168.57.1" 
      cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false, args: "-ip 192.168.57.124"
      cfg.vm.provision "reload"
      cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: false
      cfg.vm.provision "shell", path: "scripts/configure-users.ps1", privileged: false
    
      cfg.vm.provider "vmware_desktop" do |v, override|
        v.vmx["displayname"] = "sdc.private.adapt.com"
        v.memory = 3072
        v.cpus = 2
        v.gui = true
      end
    
      cfg.vm.provider "virtualbox" do |vb, override|
        vb.gui = true
        vb.name = "sdc.private.adapt.com"
        vb.default_nic_type = "82545EM"
        vb.customize ["modifyvm", :id, "--memory", 3072]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--vram", "32"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
    
      cfg.vm.provider "libvirt" do |lv, override|
        lv.graphics_type = "spice"
        lv.video_type = "qxl"
        lv.input :type => "tablet", :bus => "usb"
    
        override.vm.box = "../Boxes/windows_2016_libvirt.box"
        lv.video_vram = 32768
        lv.memory = 3072
        lv.cpus = 2
        # This is NOT the right semantic for Vagrant synced folder. It's a workaround:
        # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11
        override.vm.synced_folder '.', '/', type: 'winrm' 
        end
      end
      # ~ ------------------------------------------------------------------------------------------------------------------------------------------------------
    # @ subdomain controller 
    config.vm.define "sdc.testing.adapt.com" do |cfg|
      cfg.vm.box = "detectionlab/win2016"
      cfg.vm.hostname = "sdc-testing"
      cfg.vm.boot_timeout = 600
      cfg.winrm.transport = :plaintext
      cfg.vm.communicator = "winrm"
      cfg.winrm.basic_auth_only = true
      cfg.winrm.timeout = 300
      cfg.winrm.retry_limit = 20
      cfg.vm.network :private_network, ip: "192.168.58.124", gateway: "192.168.58.1", dns: "8.8.8.8"
      
      # scripts
      cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: true, args: "-ip 192.168.58.124 -dns 8.8.8.8 -gateway 192.168.58.1" 
      cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false, args: "-ip 192.168.58.124"
      cfg.vm.provision "reload"
      cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: false
      cfg.vm.provision "shell", path: "scripts/configure-users.ps1", privileged: false
    
      cfg.vm.provider "vmware_desktop" do |v, override|
        v.vmx["displayname"] = "sdc.testing.adapt.com"
        v.memory = 3072
        v.cpus = 2
        v.gui = true
      end
    
      cfg.vm.provider "virtualbox" do |vb, override|
        vb.gui = true
        vb.name = "sdc.testing.adapt.com"
        vb.default_nic_type = "82545EM"
        vb.customize ["modifyvm", :id, "--memory", 3072]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--vram", "32"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
    
      cfg.vm.provider "libvirt" do |lv, override|
        lv.graphics_type = "spice"
        lv.video_type = "qxl"
        lv.input :type => "tablet", :bus => "usb"
    
        override.vm.box = "../Boxes/windows_2016_libvirt.box"
        lv.video_vram = 32768
        lv.memory = 3072
        lv.cpus = 2
        # This is NOT the right semantic for Vagrant synced folder. It's a workaround:
        # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11
        override.vm.synced_folder '.', '/', type: 'winrm' 
        end
      end
end
